---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  This is a cloudformation to develop the baseline Network resources such as VPC and other sub components

Metadata: 
 AWS::CloudFormation::Interface: 
  ParameterGroups: 
    - 
      Label: 
        default: "Network Configuration"
      Parameters: 
        - VPC01P
    - 
      Label: 
        default: "Tags"
      Parameters: 
        - Environment
        - ProjectName
        - ProjectID

Parameters:
  VPC01P:
    Type: String
    Default: 10.0.0.0/16
    AllowedValues:
      - 10.0.0.0/16
      - 10.0.0.0/24
    Description: Enter the value of VPC CIDR

  Environment:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
    Description: Enter the environment type
  ProjectName:
   Type: String
   Description: Enter the name of the Project

  ProjectID:
   Type: String
   Description: Enter the name of the Project ID

Resources:
  VPC01:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPC01P
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags: 
        - Key : EnvironmentName 
          Value : !Ref Environment
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : VPC01
  
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-1a
      CidrBlock: 10.0.0.0/24
      Tags: 
        - Key : EnvironmentName 
          Value : !Ref Environment
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : PublicSubnet1
      VpcId: !Ref VPC01

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-1b
      CidrBlock: 10.0.1.0/24
      Tags: 
        - Key : EnvironmentName 
          Value : !Ref Environment
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : PublicSubnet2
      VpcId: !Ref VPC01


  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-1c
      CidrBlock: 10.0.2.0/24
      Tags: 
        - Key : EnvironmentName 
          Value : !Ref Environment
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : PublicSubnet3
      VpcId: !Ref VPC01
  
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-1a
      CidrBlock: 10.0.3.0/24
      Tags: 
        - Key : EnvironmentName 
          Value : !Ref Environment
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : PrivateSubnet1
      VpcId: !Ref VPC01

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-1b
      CidrBlock: 10.0.4.0/24
      Tags: 
        - Key : EnvironmentName 
          Value : !Ref Environment
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : PrivateSubnet2
      VpcId: !Ref VPC01

  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: us-east-1c
      CidrBlock: 10.0.5.0/24
      Tags: 
        - Key : EnvironmentName 
          Value : !Ref Environment
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : PrivateSubnet3
      VpcId: !Ref VPC01


  IG01:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key : EnvironmentName 
          Value : !Ref Environment
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref IG01
      VpcId: !Ref VPC01


  RouteTable:
   Type: AWS::EC2::RouteTable
   Properties: 
      Tags: 
        - Key : EnvironmentName 
          Value : !Ref Environment
        - Key : Project Name
          Value : !Ref ProjectName
        - Key : Project ID
          Value : !Ref ProjectID
        - Key : Resource Name
          Value : RouteTable
      VpcId: !Ref VPC01


  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties: 
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref IG01
        RouteTableId: !Ref RouteTable
  
  PublicRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref PublicSubnet1
      




